# -*- coding: utf-8 -*-
"""SVD.ipynb

Automatically generated by Colaboratory.

You can run this program using Google colab on this link
https://colab.research.google.com/drive/10DK7jQVBFXw0n64FqVvaE2XK1uXDXmwg?usp=sharing
"""

# Singular-value decomposition
import numpy
from scipy.linalg import svd
A = numpy.array([[1, 1, 1], [0, 1, 1], [0, 1, 0], [1, 0, 0], [1, 0, 0], [1, 0, 1], [1, 1, 1], [1, 1, 1], [1, 0, 1], [0, 2, 0], [0, 1, 1]])
print(A)
# SVD
U, S, VT = svd(A, full_matrices= False)
print("matrix U")
print(U)
print("Diagonal elements of matrix S")
print(S)
print("matrix VT")
print(VT)

Sk = numpy.array([[4.09887197, 0],[0, 2.3615708]])

q = numpy.array([0,0,0,0,0,1,0,0,0,1,1])
print("aAa")
print(numpy.matmul(q, U))
print("BbB")
print(numpy.matmul(numpy.matmul(q, U[:,0:2]), numpy.linalg.inv(Sk)))
#print(U[:,0:2])